# Generated by Django 4.2.3 on 2023-08-08 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='photo',
        ),
    ]
